= List ds subits et leur contenu

== GOLD 19/05
01h44    : ne pas aller au module molecule si je n'ai rien a y trouver
00h48 / 17 : amelioration endGame pour la recherche des samples
00h20 / 13: complete refactoring of the diag State !

== GOLD 18/05
17h00 / 7 : some refactroring (neutral ?)
16h30 / : utilisation de la molecule qui est la moins nombreuse

== SILBER 17/05
* 14h47 / 4  : gerer la fin de partie dans le moleculeOptimizer 
* 11h38 / 6  : correction d'un bug d'xp qui faisait qu'on bouclait vers le LAB
* 09h42 / 6  : moleculeOptimiser : prendre en compte les xp que je vais gagner
* 03h00 / 15 : faire les 2 greedy : dabord sur les futurs sample, puis sur mon manque d'xp
* 02h45 / 20 : plutot que greedy sur les molecules des samples a venir, greedy sur les molecule ou j'ai moins d'xp
* 02h30 / 16 : revert du code pour optimiser + prendre plus de molecules
* 01h30 / 49 : Avec le code pour optimiser les samples au DIAG
* 00h55 / 25 : correction d'un bug sur le blocking
* 00h32 / 43 : ajout du sampleOptimiser (pour test perf uniquement)

== SILVER 16/05
* 00h00 / 37 : pas de changement
* 17h30 / 25 : refactoring sans changement
* 16h00 / 28 : resubmit pour variance
* 15h45 / 29 : correction du Sample.PointsWON (il faut faire des T.Us !!!)
* 15h20 / 26 : submit avec le code de 02h37 pour voir
* 14h45 / 33 : idem
* 14h30 / 42 : ne plus choisir les samples dans l'ordre au LAB, choisir celui rapporte le plus de points en + (à tour == 400, ca peut améliorer le truc)
* 14h00 / 25 : reword + work on sample Optimizer 
* 02h37 / 14 : Optimisation de la prise des molecules
* 01h24 / 12 : correction bug sur l'optimizer ! + tentative d'utiliser les science projects

== SILVER 15/05
* 23h07 / 49 : blocage si on peut prendre une molecule unique
 